 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chirps", type: :request do
  # Chirp. As you add validations to Chirp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Chirp.create! valid_attributes
      get chirps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chirp = Chirp.create! valid_attributes
      get chirp_url(chirp)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chirp_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      chirp = Chirp.create! valid_attributes
      get edit_chirp_url(chirp)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Chirp" do
        expect {
          post chirps_url, params: { chirp: valid_attributes }
        }.to change(Chirp, :count).by(1)
      end

      it "redirects to the created chirp" do
        post chirps_url, params: { chirp: valid_attributes }
        expect(response).to redirect_to(chirp_url(Chirp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Chirp" do
        expect {
          post chirps_url, params: { chirp: invalid_attributes }
        }.to change(Chirp, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post chirps_url, params: { chirp: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chirp" do
        chirp = Chirp.create! valid_attributes
        patch chirp_url(chirp), params: { chirp: new_attributes }
        chirp.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chirp" do
        chirp = Chirp.create! valid_attributes
        patch chirp_url(chirp), params: { chirp: new_attributes }
        chirp.reload
        expect(response).to redirect_to(chirp_url(chirp))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        chirp = Chirp.create! valid_attributes
        patch chirp_url(chirp), params: { chirp: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chirp" do
      chirp = Chirp.create! valid_attributes
      expect {
        delete chirp_url(chirp)
      }.to change(Chirp, :count).by(-1)
    end

    it "redirects to the chirps list" do
      chirp = Chirp.create! valid_attributes
      delete chirp_url(chirp)
      expect(response).to redirect_to(chirps_url)
    end
  end
end
